const EMAIL_SIGN_IN = "EMAIL_SIGN_IN";
const EMAIL_SIGN_IN_SUCCESS = "EMAIL_SIGN_IN_SUCCESS";
const EMAIL_SIGN_IN_FAILURE = "EMAIL_SIGN_IN_FAILURE";

const EMAIL_REGISTER = "EMAIL_REGISTER";
const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
const EMAIL_REGISTER_FAILURE = "EMAIL_REGISTER_FAILURE";

const LOGOUT = "LOGOUT";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "LOGOUT_FAILURE";

const GET_USER = "GET_USER";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILURE = "GET_USER_FAILURE";
const CLEAR_ERROR = "CLEAR_ERROR";

const FETCH_ALL_LISTS = "FETCH_ALL_LISTS";
const FETCH_ALL_LISTS_SUCCESS = "FETCH_ALL_LISTS_SUCCESS";
const FETCH_ALL_LISTS_FAILURE = "FETCH_ALL_LISTS_FAILURE";

const ADD_LIST = "ADD_LIST";
const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
const ADD_LIST_FAILURE = "ADD_LIST_FAILURE";

const DELETE_LIST = "DELETE_LIST";
const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE";

const UPDATE_LIST = "UPDATE_LIST";
const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
const UPDATE_LIST_FAILURE = "UPDATE_LIST_FAILURE";

export {
    EMAIL_SIGN_IN,
    EMAIL_SIGN_IN_SUCCESS,
    EMAIL_SIGN_IN_FAILURE,
    EMAIL_REGISTER,
    EMAIL_REGISTER_SUCCESS,
    EMAIL_REGISTER_FAILURE,
    LOGOUT,
    LOGOUT_SUCCESS,
    LOGOUT_FAILURE,
    GET_USER,
    GET_USER_SUCCESS,
    GET_USER_FAILURE,
    CLEAR_ERROR,
    FETCH_ALL_LISTS,
    FETCH_ALL_LISTS_SUCCESS,
    FETCH_ALL_LISTS_FAILURE,
    ADD_LIST,
    ADD_LIST_SUCCESS,
    ADD_LIST_FAILURE,
    DELETE_LIST,
    DELETE_LIST_SUCCESS,
    DELETE_LIST_FAILURE,
    UPDATE_LIST,
    UPDATE_LIST_SUCCESS,
    UPDATE_LIST_FAILURE
}
